---
title: "Instructions"
output: html_document
---


<html>
  <head>
    <a href="https://github.com/ices-taf/2019_4017-19_TechnicalService" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#fff; color:#151513; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
  </head>


## Introductory notes  
***


#### The seabass catch allocation tool was developed to be used exclusively for Sea bass (Dicentrarchus labrax) in divisions 4.b–c, 7.a, and 7.d–h (central and southern North Sea, Irish Sea, English Channel, Bristol Channel, and Celtic Sea).  

<br> 

#### The assumptions used in the tool are closely linked to the assessment of this stock and any attempt to use it for other stocks will not produce sensible results.  

<br> 

#### The seabass catch allocation tool was developed with the intent to aid managers and stakeholders to test multiple catch allocation schemes by gear and different regulations for recreational catches using the ICES catch advice as a maximum.  

<br> 

#### Although this tool is designed to be in line with the assumptions used in the seabass advice there are instances where it deviates from them. The tool can be used to allocate monthly options, while the assessment is run on annual time step. Also, depending on the gear options selected, the overall commercial catch at age may differ from that assumed in the ICES forecast.  

<br>  
<br>

## Instructions  
***

#### **Inputs:**  


#### 1. Choose catch advice. Two options are available:
#####     1.1) EU MAP: F~MSY~ × SSB~2020~ / MSY~Btrigger~
#####     1.2) EU MAP F~MSY~ ~lower~ × SSB~2020~ / MSY~Btrigger~
#### 2. Choose time step to be used in the allocation simulation.
#### 3.Select the management options to be applied to the recreational component (default options are the current management measures in place).
#### 4. Input catch allocation by gears in the table (in tonnes).
#### 5. Click “Run simulation” to test the allocations.

<br> 

#### Every time a change is made to any of the inputs the simulation needs to be run again by pressing `Run Simulation`  

<br> 

#### **Outputs:** 


#### On the top right it is shown a plot of catch at age in thousands by gear. The black dashed line is the catch at age for the advice given in the main ICES advice for this stock.  

<br> 

#### Below the plot, a table is shown with the results of the simulation. Since the catch allocations are not allowed to exceed the ICES advice, final catch allocations may be less than those that were inputted. For monthly simulations, catch allocations are taken each month until the advice value is reached, for subsequent months the catch is set to zero.  

<br> 

#### Finally the last table shows the summary of the forecast including the impact in the SSB and the change in advice.  The table compares the simulated catch allocations with the forecast scenarios from the ICES advice.  

<br> 
<br> 

### **Notes:**  
*** 

#### The total catch available for the commercial gears is the ICES advice less the expected recreational catch.  


#### The simulation estimates the catch at age that will lead to the tonnage specified for each gear based on an analysis of the selectivity of each gear. As such, it may not be possible to catch the exact tonnage inputted, and resulting values may differ by a few tonnes. The outputs are values rounded to the nearest tonne. 

<br>

#### Discards –discard proportions by gear (amount of the catch that is discarded) have been estimated using French and UK data from 2016 to 2018. There are insufficient data to accurately estimate discard selectivity by gear type, so the same discard selectivity as used in the ICES forecast is applied for all gears. Depending on the allocations by gear, the total amount of discards may vary from that forecasted in the ICES advice.  

<br> 

#### This tool has gone extensive debugging and error checking. Nevertheless, if you encounter any inconsistency or bug please let us know by emailing us at accessions@ices.dk
<br> 
<br> 
